name: staking_lib
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.1 <3.0.0'



dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner:
dependencies: {crypto: ^3.0.2, json_serializable: ^6.3.1,json_annotation: ^4.6.0, cryptography: ^2.0.5, hex: ^0.2.0}
